### PR TITLE
Fix issue with keyword arguments under Ruby 3

### LINKED ISSUE #331: Reverting breaks on Ruby 3 due to keyword changes, solution is relatively easy
Hi 👋 so the way the command recorder methods record their result, cause the migrations to error when reverting a migration on Ruby 3. Eg here is a method that is incorrect:

https://github.com/scenic-views/scenic/blob/v1.5.4/lib/scenic/command_recorder.rb#L14-L16

```ruby
module Scenic
  module CommandRecorder
    # ...
    def update_view(*args)
      record(:update_view, args)
    end
  end
end
```

After a lot of research (eg @eregon's blog [here](https://eregon.me/blog/2021/02/13/correct-delegation-in-ruby-2-27-3.html)), I've come to the conclusion that the way to fix this across all the relevant Ruby versions is to conditionally use `ruby2_keywords`:

```diff
module Scenic
  module CommandRecorder
    # ...
    def update_view(*args)
      record(:update_view, args)
    end
+   ruby2_keywords : update_view if respond_to?(:ruby2_keywords, true)
  end
end
```

There's a lot of additional detail in ([this](https://github.com/rails/rails/issues/42653)) bug in ActiveRecord, where I initially reported it.

But you can run the test suite on 2.7 with `env RUBYOPT=-W:deprecated rake` and it will emit warnings where this error occurs. In Ruby 3 , each of those warnings actually explodes. It's pretty confusing to trace them back to Scenic's definition 

env RUBYOPT=-W:deprecated rake

Or you can run it on Ruby 3, it will actually fail in those spots 😜

image

### PR DESCRIPTION
**Pull request by derekprior**
Ruby 3 changed the handling of keyword arguments in a way that broke our
liberal handling of arguments in the command recorder. Using
`ruby2_keywords` helps us fix this while maintaining compatibility with
older (pre 2.7) versions of Ruby.

In the next major version of Scenic, we should drop support for rubies
older than either 2.7 or 3.0 to avoid carrying this fix forward.

Fixes #331. For more context on why this is the solution, see:

* https://eregon.me/blog/2021/02/13/correct-delegation-in-ruby-2-27-3.html
* https://github.com/rails/rails/issues/42653

### CODE REVIEW

File: lib/scenic/command_recorder/statement_arguments.rb [hunk 1]
```diff
@@ -36,15 +36,25 @@ def options
         @options ||= @args[1] || {}
       end
 
+      def keyword_hash(hash)
+        if Hash.respond_to? :ruby2_keywords_hash
```
Comment (derekprior) [inline lib/scenic/command_recorder/statement_arguments.rb:40]: @JoshCheek's original version conditionally defined this method, which means we don't have to call `respond_to?` every time call `keyword_hash` but `def`ing the method once is more aesthetically pleasing and overall less complex. Given that there is no performance concern with migrations, I think this is the right tradeoff.
